version: '3'
services:
  web:
    build:
      context: ./WEB
    ports:
     - "5000:5000"
    depends_on:
     - mongo
     - manage
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
  manage:
    build: ./MANAGE
    depends_on:
     - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    volumes:
      - ./mongo_man
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo_db

    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: example