#docker-compose version
version: '2.4'

services:
  web: #defines the main flask application enclosure
    container_name: sms-flask
    build:
      context: ./
      dockerfile: ./WEB/Dockerfile
    ports:
      #restricts to localhost, remove the ip prefix to allow public access
      - 5000:5000
    depends_on:
      - mongo
      - manage
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      #Should only be used for debugging.
      # FLASK_DEBUG: 1
      PYTHONUNBUFFERED: 1
      #End of debugging config
    #Mounts the app image to the source, to allow dynamic updates of the flask app.
    #Should only be used for debugging.
    #volumes:
    #  - ./WEB:/usr/src/app/WEB
    #  - ./SHARED:/usr/src/app/SHARED
    #End of debugging config
  twitter: #defines the main flask application enclosure
    container_name: sms-twitter
    build:
      context: ./
      dockerfile: ./TWITTER/Dockerfile
    ports:
      #restricts to localhost, remove the ip prefix to allow public access
      - 5001:5001
    depends_on:
      - mongo
      - manage
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      #Should only be used for debugging.
      # FLASK_DEBUG: 1
      PYTHONUNBUFFERED: 1
      #End of debugging config
      TWITTER_API_KEY: ${TWITTER_API_KEY}
      TWITTER_API_ACCESS_KEY: ${TWITTER_API_ACCESS_KEY}
    #Mounts the app image to the source, to allow dynamic updates of the flask app.
    #Should only be used for debugging.
    #volumes:
    #  - ./TWITTER:/usr/src/app/TWITTER
    #  - ./SHARED:/usr/src/app/SHARED
    #End of debugging config

  mongo: #defines the mongoDB enclosure
    image: mongo:4.0.5
    container_name: sms-mongodb
    restart: always
    volumes:
      #allows the database to persist when shutdown / across builds
      - symptomsurvey_db_volume:/data/db
      #- type: volume
      #  target: /data/db
      #  source: symptomsurvey_db_volume
    ports:
      - 27017:27017

  manage: #defines a node enclosure for interacting with the mongo database
    container_name: sms-mongodb-manager
    build:
      context: ./
      dockerfile: ./MANAGE/Dockerfile
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      ADD_DEBUG_RECORDS: "True" # True for debugging, inserts test users

volumes:
  symptomsurvey_db_volume:
